### -*- coding: utf-8 -*-
##"""spinal_pain.ipynb
##
##Automatically generated by Colaboratory.
##
##Original file is located at
##    https://colab.research.google.com/drive/1SaTDKiLunr4Js_ZHS__SYn2S5uIawnmH
##"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LogisticRegression
df = pd.read_csv('Dataset_spine.csv')
df.head()
#print(df)

#plot
plt.scatter(df.Col1,df.Class_att,marker='+',color='red')
plt.show()

#train import

x = df.drop(['Class_att'], axis=1)
y = df.Class_att

x_train, x_test, y_train, y_test = train_test_split(x,y,train_size=0.8)
x_test.head()
#print('x test',x_test)
#print('x train',x_train)
#print('y test',y_test)
#print('y train',y_train)

model = LogisticRegression()
model.fit(x_train, y_train)

print('output of x_test:',model.predict(x_test))
print('accuracy',model.score(x_test,y_test))

print('probability :',model.predict_proba(x_test))#prob of abnormal  product or normal.

print(model.predict([[56]]))#when thw errorr like model is not run or dimenation error you can simply solve this by adding brakets.
#it consider that 56 age and that's why index array reqaire.
